---
gh_api_token:
  item: GitHub Ansible-token
  args:
    field: credential
    vault: Minervous

os_map:
  Darwin: osx
  Windows: win

arch_map:
  x86_64: x64
  arm64: arm64

platform: "{{ os_map.get(ansible_facts['os_family'], 'linux') }}-{{ arch_map.get(ansible_facts['architecture'], 'x64') }}"

sha_pattern: "^.*<!-- BEGIN SHA {{ platform }} -->([^<]+)<!-- END SHA {{ platform }} -->.*$"
