---
- hosts: localhost
  roles:
    - install_sshpass

- hosts: github_runners
  vars:
    github_target: 'minervous'  # This is an organization, but could be 'owner/some-repo' instead
    gha_runner:
      name: "{{ inventory_hostname }}"
      group:
      labels: []
  roles:
    - role: remote_admin
      when: ansible_facts['os_family'] != 'Windows'
    - github_actions_runner
