---
ungrouped:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: '/usr/bin/env python'

github_runners:
  hosts:
    locomotive:
      ansible_connection: winrm
      ansible_winrm_port: 5985
      ansible_python_interpreter: 'python.exe'
      ansible_host: "{{ lookup('community.general.onepassword', 'Locomotive', vault='Local', field='url') }}"
      ansible_user: "{{ lookup('community.general.onepassword', 'Locomotive', vault='Local', field='username') }}"
      ansible_password: "{{ lookup('community.general.onepassword', 'Locomotive', vault='Local', field='password') }}"

    macmini_m1:
      ansible_host: "{{ lookup('community.general.onepassword', 'Mac mini M1', vault='Local', field='url') }}"
      ansible_user: "{{ lookup('community.general.onepassword', 'Mac mini M1', vault='Local', field='username') }}"
      ansible_become_password: "{{ lookup('community.general.onepassword', 'Mac mini M1', vault='Local', field='password') }}"
      ansible_python_interpreter: '/usr/bin/env python3'
